spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: myGroup
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9092
  application:
    name: Kafka-Sample
logging:
  level:
    com.kafka: INFO
server:
  port: ${SERVER_PORT:8080}





